######################################################################
#
# File name : eyeriss_qgl_compile.do
# Created on: Wed Oct 04 21:02:28 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../../../GNNacc/eyeriss/conv1_3.v" \
"../../../../../../../GNNacc/eyeriss/eyeriss_qgl.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

